apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  completions: 6
  parallelism: 3
  activeDeadlineSeconds: 100
  template:
    metadata:
      name: example-job
    spec:
      containers:
      - name: p1
        image: perl
        command: ["perl"]
        args: ["-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
