---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: existing-pd-pv
spec:
  storageClassName: ""
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: quickstart-pd
    fsType: ext4
