---
apiVersion: v1
kind: Service
metadata:
  name: ns-demo
  namespace: demo-ns
spec:
  type: LoadBalancer
  selector:
    app: ns-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-demo
  namespace: demo-ns
  labels:
    app: ns-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ns-demo
  template:
    metadata:
      namespace: demo-ns
      labels:
        app: ns-demo
    spec:
      containers:
      - name: ns-demo
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080
