---
#  FYI: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/secretGeneratorPlugin.md
configMapGenerator:
  - name: config
    files:
      - fromfile.properties
    literals:
      - fromliteral=test2
resources:
  - hello.yaml
