---
#  FYI: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/secretGeneratorPlugin.md
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: secret
    files:
      - fromfile.properties
    literals:
      - fromliteral=test2
resources:
  - hello.yaml
