---
apiVersion: v1
kind: Service
metadata:
  name: volume-demo
spec:
  type: LoadBalancer
  selector:
    app: volume-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-demo
  labels:
    app: volume-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volume-demo
  template:
    metadata:
      labels:
        app: volume-demo
    spec:
      containers:
      - name: volume-demo
        image: gcr.io/google-samples/hello-app:1.0
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
        ports:
        - containerPort: 8080
      volumes:
        - name: cache-volume
          emptyDir: {}
